baseURL = "https://safish.github.io/"
languageCode = "en-us"
title = "Safia Malik"
theme = "hugo-resume-master"

[params]
    firstName = "Safia"
    lastName = "Naureen Malik"
    address = "Soil & Water Conservation Research Institute, Chakwal"
    phone = "+92-331-5182743"
    contactNote = "Soil Scientist"
    profileImage = "img/me.png"
    email = "safiamalik6@gmail.com"
    description = "Working as Assistant Research Officer (Soil Science ) at Soil and Water Conservation Research Institute Chakwal from last six years. I am well equipped with modern techniques in the field of Soil Science, Particularly in the field of land and water management, soil fertility/soil health, rainfed agriculture, water saving techniques and efficient use of stored rainwater. I have ability to work in all situations either in field, lab or official matters/correspondence. I am also involve in capacity building of farmers, professionals and service providers in the field of land and water management including rainwater harvesting techniques, high efficiency irrigation system (HEIS: drip, bubbler), soil conservation from soil erosion through rainwater, on-farm preparation of compost and its use for improvement in soil health."

    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true
    showConferance = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/eddiewebb/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/eddiewebb/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/82880"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/edwardawebb"
    icon = "keybase"

[params.google.analytics]
    trackerID = "XX-123446-01"
